steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        mkdir -p /root/.ssh &&
        echo "$SSH_PRIVATE_KEY" &&
        echo "$SSH_PUBLIC_KEY"
    secretEnv: ['SSH_PRIVATE_KEY', 'SSH_PUBLIC_KEY']

    env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'BUILD_ID=$BUILD_ID'

secrets:
  - kmsKeyName: 'projects/$PROJECT_ID/locations/global/keyRings/visionworkers/cryptoKeys/visionworkers'
    secretEnv:
      SSH_PRIVATE_KEY: 'projects/$PROJECT_ID/secrets/visionw-ssh-private-key/versions/latest'
      SSH_PUBLIC_KEY: 'projects/$PROJECT_ID/secrets/visionw-ssh-public-key/versions/latest'
