steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        mkdir -p /builder/home/.ssh &&
        echo "$SSH_PRIVATE_KEY" > /builder/home/.ssh/google_compute_engine &&
        chmod 600 /builder/home/.ssh/google_compute_engine &&
        echo "$SSH_PUBLIC_KEY" > /builder/home/.ssh/google_compute_engine.pub &&
        chmod 644 /builder/home/.ssh/google_compute_engine.pub
    env:
      - SSH_PRIVATE_KEY=$_SSH_PRIVATE_KEY
      - SSH_PUBLIC_KEY=$_SSH_PUBLIC_KEY

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'scp', '--recurse', './', 'a100-cuda118:~/', '--zone', 'us-central1-f']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'a100-cuda118', '--zone', 'us-central1-f', '--command', 'bash ~/build_docker_image.sh']
    env:
    - PROJECT_ID=$PROJECT_ID
    - BUILD_ID=$BUILD_ID
