steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        mkdir -p /builder/home/.ssh &&
        echo "$SSH_PRIVATE_KEY"
    secretEnv:
      - SSH_PRIVATE_KEY

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'scp', '--recurse', '*', 'a100-cuda118:~/', '--zone', 'us-central1-f']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'a100-cuda118', '--zone', 'us-central1-f', '--command', 'bash ~/build_docker_image.sh']
    env:
      - PROJECT_ID=$PROJECT_ID
      - BUILD_ID=$BUILD_ID

options:
  logging: 'CLOUD_LOGGING_ONLY'

secrets:
  - secretEnv:
      SSH_PRIVATE_KEY: 'projects/183466620446/secrets/test-vision-workers'
