FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Installing necessary packages
RUN apt-get update && apt-get install -y wget git curl lsof procps\
    && curl -sL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g pm2

# Installing/setting up Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && chmod 700 Miniconda3-latest-Linux-x86_64.sh \
    && ./Miniconda3-latest-Linux-x86_64.sh -b \
    && rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH="/root/miniconda3/bin:${PATH}"

RUN conda create -n venv python=3.10.13 -y \
    && echo "source activate venv" > ~/.bashrc

ENV PATH="/root/miniconda3/envs/venv/bin:${PATH}"

# Installing CUDA toolkit
RUN CUDA_VERSION="11.8.0" && \
    CUDA_VERSION_MAJOR=$(echo $CUDA_VERSION | cut -d'.' -f1) && \
    CUDA_VERSION_MINOR=$(echo $CUDA_VERSION | cut -d'.' -f2) && \
    CUDA_VERSION_SIMPLE="${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}.0" && \
    conda install nvidia/label/cuda-${CUDA_VERSION_SIMPLE}::cuda-toolkit -y

# Vllm patch for cuda118
COPY cu118_vllm_patch.sh /app/cu118_vllm_patch.sh
RUN chmod +x /app/cu118_vllm_patch.sh \
    && /app/cu118_vllm_patch.sh

# llm server requirements
COPY llm_server/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt \
    && pip install huggingface_hub[hf_transfer]

COPY llm_server/ /app/llm_server

RUN chmod +x /app/llm_server/entrypoint.sh

ENV HF_HUB_ENABLE_HF_TRANSFER=1

ARG SERVER_PORT=6919
ENV CURRENT_SERVER_PORT=${SERVER_PORT}
EXPOSE $CURRENT_SERVER_PORT

RUN mkdir /app/cache
ENV HF_HOME=/app/cache

CMD ["sh", "-c", "cd /app/llm_server && ./entrypoint.sh"]

