#!/bin/bash

# THIS FILE CONTAINS ACTIONS TO BE PERFORMED FOR ORCHESTRATOR SERVER AT GIT UPDATE

# THIS FILE CONTAINS THE STEPS NEEDED TO AUTOMATICALLY UPDATE THE REPO ON A TAG CHANGE
# THIS FILE ITSELF MAY CHANGE FROM UPDATE TO UPDATE, SO WE CAN DYNAMICALLY FIX ANY ISSUES

# SOME STEPS ARE COMMENTED OUT IN THIS UPDATE AS THEY ARE NOT NEEDED

echo "Just some changes"

/validator_orchestrator/entrypoint.sh